swagger: '2.0'
info:
  title: fkscholarshipapp
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - text/html

x-google-allow: all
x-google-backend:
  address: https://us-central1-fkscholarshipapp.cloudfunctions.net/UserAccess

securityDefinitions:
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    # Optional. Replace YOUR-CLIENT-ID with your client ID
    x-google-audiences: "2587253159-l3mljeof06hdf61v3aaej64vu1rjmumf.apps.googleusercontent.com"

paths:
  /user:
    post:
      summary: update user data
      operationId: userpost
      security:
        - google_id_token: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              message:
                type: string
                description: The message to be posted 
    get:
      summary: get the user data
      operationId: userget
      security:
        - google_id_token: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        disable_auth: true
        address: https://storage.googleapis.com/fkscholarshipapp_testsite/index.html
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /{item}:
    get:
      summary: Greet a user
      operationId: bucket
      parameters:
        - name: item
          in: path
          description: a path to an item in bucket
          type: string
          required: true
      x-google-backend:
        disable_auth: true
        address: https://storage.googleapis.com/fkscholarshipapp_testsite
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - google_id_token: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /application/{item}:
    get:
      summary: Greet a user
      operationId: userapp
      parameters:
        - name: item
          in: path
          description: a path to an item in bucket
          type: string
          required: true
      x-google-backend:
        disable_auth: true
        address: https://storage.googleapis.com/fkscholarshipapp_testsite
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - google_id_token: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /icons/{item}:
    get:
      summary: Greet a user
      operationId: icons
      parameters:
        - name: item
          in: path
          description: a path to an item in bucket
          type: string
          required: true
      x-google-backend:
        disable_auth: true
        address: https://storage.googleapis.com/fkscholarshipapp_testsite
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - google_id_token: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string